[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "MyPackage"
version = "1.0"

[tool.pytest.ini_options]
addopts = "--cov=MyPackage"
testpaths = [
    "tests",
]